# pacman-aarch64.conf
# bootstrapping configuration

[options]
Architecture = aarch64
ParallelDownloads = 5
SigLevel = Never

[core]
Server = http://mirror.yandex.ru/archlinux-arm/$arch/$repo

[extra]
Server = http://mirror.yandex.ru/archlinux-arm/$arch/$repo

[alarm]
Server = http://mirror.yandex.ru/archlinux-arm/$arch/$repo
