# DO NOT EDIT THIS FILE
#
# Please edit /boot/bootEnv.txt to set supported parameters
#
# Recompile with:
# mkimage -C none -A arm64 -T script -d /boot/boot.cmd /boot/boot.scr

setenv load_addr "0x45000000"
setenv overlay_error "false"
setenv ramdisk_error "false"
# default values
setenv rootfstype "ext4"
setenv docker_optimizations "on"
setenv rootdev "/dev/mmcblk0p1"
setenv consoleargs "console=ttyS0,115200 console=tty1"
setenv kernel_file "Image"
setenv ramdisk_file "uInitrd"

# Print boot source
itest.b *0x10028 == 0x00 && echo "U-boot loaded from SD"
itest.b *0x10028 == 0x02 && echo "U-boot loaded from eMMC or secondary SD"
itest.b *0x10028 == 0x03 && echo "U-boot loaded from SPI"
echo "Boot script loaded from ${devtype}"

# Load environment file
if test -e ${devtype} ${devnum} ${prefix}bootEnv.txt; then
    echo "Loading variables from bootEnv.txt"
	load ${devtype} ${devnum} ${load_addr} ${prefix}bootEnv.txt
	env import -t ${load_addr} ${filesize}
fi

# Define kernel command-line arguments
setenv bootargs "root=${rootdev} rootfstype=${rootfstype} rootwait ${consoleargs} consoleblank=0 usb-storage.quirks=${usbstoragequirks} ${extra_cmdline}"

# misc tweaks
if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=memory swapaccount=1"; fi

# Load kernel, initramfs and device tree
load "${devtype}" "${devnum}" "${kernel_addr_r}" "${prefix}${kernel_file}"
load "${devtype}" "${devnum}" "${ramdisk_addr_r}" "${prefix}${ramdisk_file}" || setenv ramdisk_error "true"
load "${devtype}" "${devnum}" "${fdt_addr_r}" "${prefix}dtb/${fdtfile}"
fdt addr "${fdt_addr_r}"

# Apply DT overlays, need correspoding fixup script
if test -n "${overlays}${user_overlays}"; then
	fdt resize 65536
	for overlay in ${overlays}; do
		if load "${devtype}" "${devnum}" "${scriptaddr}" "${prefix}dtb/${overlay_path}/overlay/${overlay_prefix}-${overlay}.dtbo"; then
			echo "Applying kernel provided DT overlay ${overlay_prefix}-${overlay}.dtbo"
			fdt apply "${scriptaddr}" || setenv overlay_error "true"
		fi
	done

	for overlay in ${user_overlays}; do
		if load "${devtype}" "${devnum}" "${scriptaddr}" "${prefix}overlay-user/${overlay}.dtbo"; then
			echo "Applying user provided DT overlay ${overlay}.dtbo"
			fdt apply "${scriptaddr}" || setenv overlay_error "true"
		fi
	done

	if test "${overlay_error}" = "true"; then
		echo "Error applying DT overlays, restoring original DT"
		load "${devtype}" "${devnum}" "${fdt_addr_r}" "${prefix}dtb/${fdtfile}"
	else
		if load "${devtype}" "${devnum}" "${scriptaddr}" "${prefix}dtb/${overlay_path}/overlay/${overlay_prefix}-fixup.scr"; then
			echo "Applying kernel provided DT fixup script ${overlay_prefix}-fixup.scr"
			source "${scriptaddr}"
		fi
		if test -e "${devtype}" "${devnum}" "${prefix}fixup.scr"; then
			if load "${devtype}" "${devnum}" "${scriptaddr}" "${prefix}fixup.scr"; then
				echo "Applying user provided DT fixup script fixup.scr"
				source "${scriptaddr}"
			fi
		fi
	fi
fi

# Boot
if test "${ramdisk_error}" = "true"; then
    echo "Booting regardless of the ramdisk error"
    booti "${kernel_addr_r}" - "${fdt_addr_r}"
else
    booti "${kernel_addr_r}" "${ramdisk_addr_r}" "${fdt_addr_r}"
fi